### ISSUE TITLE
Alpha testing

### ISSUE THREAD

**Issue by llayman** [uncw-hfcs/ids-simulator#37]
- [ ] Prepare ALL materials needed for experiment
- [ ] Run through entire apparatus with one to two people
- [ ] Document all bugs and improvements needed
